id: AD7278AD8
title: 'The Treasure of Wisdom Illumination: A Prayer to the Omniscient Sun of the
  Teachings Sonam Senge'
type: translation
pechas:
- I531D36D4
- I17C2DB8B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:57:31.063499
  last_modified_at: 2023-01-04 11:57:31.063510
  collections:
  - Gorampa Sonam Senge
  - Works of Tibetan Masters
alignment_to_base:
  I531D36D4/72AD: 85CE
  I17C2DB8B/3D95: 85CE
